### PR TITLE
Mapping updated for Kwak̓wala

### PR DESCRIPTION
**Pull request by dacerron**
Pull request template for adding a new language
-----------------------------------------------

*Do not use this for other types of pull requests*

* **Please check if the PR fulfills these requirements**
- [x] Mapping files are added in `g2p/mappings/langs`
- [x] Mapping is either added to an existing folder or a new folder has been added
- [x] Language folder and files use appropriate [ISO 639-3 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-3_codes)
- [x] Config.yaml file includes all author names, and settings necessary
- [x] Please add some test data in `g2p/tests/public/data`. The added file should be a csv/tsv/psv file and each row should have the format `[input_mapping_code,output_mapping_code,input_string,output_string]`
- [x] As the last step, G2P has been updated by running `g2p update` locally and committing the change
- [x] You agree to license your contribution under the same license as this project (see [LICENSE](https://github.com/roedoejet/g2p/blob/master/LICENSE) file).

* **Other information**:
Pull request added for changing mappings in Kwak̓wala with guidance from Daisy Rosenblum

### CODE REVIEW

**Comment by joanise** [comment]
Second request: `g2p/mappings/langs/kwk/config.yaml` should be update to say that Olivia (and/or anyone else?) is now a co-author with Fineen Davis of the `kwk_boas_to_umista.csv` mapping.

Multiple authors a listed in this format:
```
  - display_name: Kwak'wala (Boas) to Umista
    mapping: kwk_boas_to_umista.csv
    in_lang: kwk-boas
    out_lang: kwk-umista
    rule_ordering: apply-longest-first
    prevent_feeding: true
    authors:
      - Fineen Davis
      - author 2 - presumably Olivia Chen
      - author 3 - if applicable
    <<: *shared
```

**Comment by joanise** [comment]
Thank you for this contribution, we'll be happy to merge it in with proper testing and attribution of the work!

**Comment by joanise** [comment]
I ran the tests with your latest changes, and some tests are not passing. In `g2p/g2p/tests`, running `./test_cli.py` or `./test_langs.py` reports:
```
$ ./test_cli.py
WARNING - test_cli.py: kwk-boas->kwk-umista mapping error: 'laᵋlăe' should map to 'laʼla̱i', got 'laʼla̱ʼe' (with ['--tok', '--check']).
WARNING - test_cli.py: kwk-boas->kwk-umista mapping error: 'k!waxʟ\u0323aᵋye' should map to 'kʼwax̱dɬaʼyi', got 'kʼwax̱dłaʼyi' (with ['--tok', '--check']).

$ ./test_langs.py
WARNING - test_langs.py: mapping error: laᵋlăe from kwk-boas to kwk-umista should be laʼla̱i, got laʼla̱ʼe
WARNING - test_langs.py: mapping error: k!waxʟ\u0323aᵋye from kwk-boas to kwk-umista should be kʼwax̱dɬaʼyi, got kʼwax̱dłaʼyi
```

Both are reporting the same discrepancy between the g2p output for those two words and what is stated as the expected output in the test file in `g2p/g2p/tests/public/data/kwk.psv`. If you are confident the new output is correct, you can submit an update to `kwk.psv`, and I also encourage you to add more words in that test file, to exercise your changes on a number of words and the known correct correspondance.

**Comment by joanise** [comment]
Also, I've rebased your changes at the tip of the current master, you're welcome to continue your work from `dev.kwk-updates`. It has exactly your commits, but applied after all the other changes we've made instead of before.

**Comment by roedoejet** [comment]
Hi @dacerron - thanks again for this. Any luck addressing the issue that @joanise mentions above? The PR is stale now since the main branch has changed. It might be best to close this temporarily and open a new PR when the tests are passing. Let me know what you want to do though - thanks so much again!

**Comment by roedoejet** [comment]
> Apologies for the delay on this, I have resolved conflicts with the changes in main and added test data as well as adding authors to the config.yaml. Both test_langs.py and test_cli.py are passing on my local.

Awesome @dacerron - no worries at all! I'll merge this and it should be live on https://g2p-studio.herokuapp.com momentarily. It'll also be included in our next release (planned for around June). Thanks so much again!

**Review by roedoejet — APPROVED** [review]
Thanks @dacerron

**Comment by roedoejet** [comment]
I'd actually like to close this PR, rebase it on to main to resolve the conflicts with `langs.pkl`, and merge from the new PR https://github.com/roedoejet/g2p/pull/236 since I don't have write access to cedarspace:master - @joanise can you confirm I've rebased correctly [here](https://github.com/roedoejet/g2p/pull/236) and merge?

**Pull request closed without merging**
