### PR TITLE
New langs mapping: csw and crm

### PR DESCRIPTION
**Pull request by deltork**
Pull request template for adding a new language
-----------------------------------------------

*Do not use this for other types of pull requests*

* **Please check if the PR fulfills these requirements**
- [x] Mapping files are added in `g2p/mappings/langs`
- [x] Mapping is either added to an existing folder or a new folder has been added
- [x] Language folder and files use appropriate [ISO 639-3 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-3_codes)
- [x] Config.yaml file includes all author names, and settings necessary
- [x] Please add some test data in `g2p/tests/public/data`. The added file should be a csv/tsv/psv file and each row should have the format `[input_mapping_code,output_mapping_code,input_string,output_string]`
- [x] As the last step, G2P has been updated by running `g2p update` locally and committing the change

* **Other information**:

### CODE REVIEW

**Comment by roedoejet** [comment]
Thanks so much @deltork and @bradley-ellert ! This is fantastic to add `crm` and `csw`! It looks like there isn't any data in the test data files though (`g2p/tests/public/data/crm.psv` and `g2p/tests/public/data/csw.psv`). Because I'm not familiar with the languages, is it possible for you to add some test data here that would be representative of the types of transformations you expect to do with these mappings? That way we can help ensure not to introduce any breaking changes for your mappings! Thanks again.

**Comment by deltork** [comment]
Sorry I thought I had push my test data before submitting the pull request.. you have have rerun g2p update on your end

**Comment by roedoejet** [comment]
> Sorry I thought I had push my test data before submitting the pull request.. you have have rerun g2p update on your end

No worries, thanks @deltork ! By the way, the main repo has introduced a breaking change on one of the config variables, `as_is`. As of https://github.com/roedoejet/g2p/pull/52 we renamed it to `rule_ordering`. 

These are the equivalent settings:

`as_is: true` is equal to `rule_ordering: as-written`
`as_is: false` is equal to `rule_ordering: apply-longest-first`

I'll merge your PR, and then update the configs on your mappings, so this is just fyi! Thanks again Del.

**Comment by deltork** [comment]
excellent!

**Pull request merged**
