### PR TITLE
Add CI testing on Windows

### PR DESCRIPTION
**Pull request by joanise**
Add a second test job in CI to run the test suite on Windows too, since we intend to support Windows.

### CODE REVIEW

**Comment by dhdaines** [comment]
Oh wow!  You can do that?!  This will solve many problems for me...

**Comment by joanise** [comment]
Yeah, I just decided to search for this. GitHub belongs to MS now, after all, so I thought it couldn't not be supported...

**Review by dhdaines — APPROVED** [review]

**Comment by joanise** [comment]
`windows-latest` is the latest version of Windows Server, (2022 right now), so it's not the same machine normal users would use, but it's still in the Windows ecosystem and I can already see that it's catching those errors due to not declaring the encoding when you open a file.

**Comment by joanise** [comment]
@dhdaines All the available OS choices are documented here: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Review by roedoejet — APPROVED** [review]

**Pull request merged**
