### PR TITLE
CRL completed!

### PR DESCRIPTION
**Pull request by deltork**
If it passes the tests, could you push the mapping to crj as well.

### CODE REVIEW

**Comment by roedoejet** [comment]
Thanks Del! Is the mapping the same for crj as crl? How do you mean push it?

**Comment by deltork** [comment]
> Thanks Del! Is the mapping the same for crj as crl? How do you mean push it?

yes we could just copy and paste the mappings from crl to crj

**Comment by roedoejet** [comment]
Done: e116594

**Comment by roedoejet** [comment]
And 3be6d7b, woops!

**Pull request merged**
