### PR TITLE
Update kwk_boas_to_umista.csv

### PR DESCRIPTION
**Pull request by soghomon-b**
Pull request template for adding a new language
-----------------------------------------------

*Do not use this for other types of pull requests*

* **Please check if the PR fulfills these requirements**
- [x] Mapping files are added in `g2p/mappings/langs`
- [x] Mapping is either added to an existing folder or a new folder has been added
- [x] Language folder and files use appropriate [ISO 639-3 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-3_codes)
- [x] Config.yaml file includes all author names, and settings necessary
- [x] Please add some test data in `g2p/tests/public/data`. The added file should be a csv/tsv/psv file and each row should have the format `[input_mapping_code,output_mapping_code,input_string,output_string]`
- [x] As the last step, G2P has been updated by running `g2p update` locally and committing the change
- [x] You agree to license your contribution under the same license as this project (see [LICENSE](https://github.com/roedoejet/g2p/blob/main/LICENSE) file).

* **Other information**:

### CODE REVIEW

**Comment by soghomon-b** [comment]
adding community-reviewed mappings to kwak'wala boas to umista

**Comment by joanise** [comment]
I have question: this PR would introduce the only upper case letter in this mapping. Was it meant to be for the lowercase `g` with a  dot under instead?

**Comment by soghomon-b** [comment]
Hello,
Thanks for your reply.
We noticed that g2p isn't working well with upper case letters. Do you have
a suggestion on how to fix this?

**Comment by joanise** [comment]
Ah, I see. Let me consult with my colleagues and I'll get back to you.

Would you have expected to be able to provide mixed case BOAS input and get mixed case Umista output?

**Comment by joanise** [comment]
@soghomon-b I should add, when I look at the mapping, though, it is clear to me that the authors of this mapping expected to online find lowercase letters in the input. Upper case letters are simply not handled. If you help us understand how you expect upper case letters to be handled, we should be able to adjust things for you.

**Comment by soghomon-b** [comment]
Yes, we need to preserve the cases, since they represent the beginning of
the sentence or proper nouns. Thank you!

Kindest Regards,

*Saughmon Boujkian *

University of British Columbia '25.6

**Comment by soghomon-b** [comment]
As explained above, the same conversions of lower-case letters should be
handled with upper-case ones while preserving the case.

Kindest Regards,

*Saughmon Boujkian *

University of British Columbia '25.6

United World College Dilijan '21

**Comment by joanise** [comment]
OK, thanks for the extra information, we'll take a look and see how we can handle this.

And just to make sure we do things right, what I'm understanding is that the handling of each letter should be identical, whether it is in lower or upper case, with the output respecting the case of the input.

**Comment by soghomon-b** [comment]
Exactly, thank you so much!

Kindest Regards,

*Saughmon Boujkian *

University of British Columbia '25.6

**Comment by joanise** [comment]
By the way, I would like to let you know I did not forget about this. I have a plan, but also a long list of tasks. I expect to get to this in the next couple weeks.

**Comment by soghomon-b** [comment]
Hello,
Sorry for the late reply, I was on vacation. Thanks for remembering,
looking forward to seeing the outcome.

Kindest Regards,

*Saughmon Boujkian *

University of British Columbia '25.6

**Comment by joanise** [comment]
Dear Saughmon,
I don't know how you've been using the software. Are you using the published g2p-studio or something else online, or are you working with a local installation? If you've installed it locally, I have a patch that is ready to test. See #269. You can test it by cloning your own sandbox of g2p and installing from branch dev.kwk-cap-boas-umista, again assuming you've been working from a local installation of the software.
Before I merge my PR in, I'd love to get feedback from you and the community members you work with, if that's possible. And if you have further issues after we merge it in, just reach back out to us with sample inputs and how they should be converted, and we'll work on fixing the mapping.
Cheers,
Eric

**Comment by joanise** [comment]
Closing this PR as #303 fixes the problem in a more general way.

**Pull request closed without merging**
