### PR TITLE
Dev.shank

### PR DESCRIPTION
**Pull request by shankhalika-katya**
added tonal vowels and nasalized vowels

### CODE REVIEW

**Comment by roedoejet** [comment]
Hey @shankhalika-katya, looks good, but it doesn't look like you ran `g2p update` on this yet, can you run that and push the updated files?

**Comment by shankhalika-katya** [comment]
just ran it, does it look alright?

**Comment by roedoejet** [comment]
Cool, so after you run g2p update, if you run `git status` in the repo, you should see a few files that it will have changed. So then you should commit those files (`git commit -a -m "chore: ran g2p update"` for example. Make sense?

**Comment by roedoejet** [comment]
Awesome! thanks @shankhalika-katya !

**Review by roedoejet — APPROVED** [review]

**Pull request merged**
