### PR TITLE
API v2, second time around

### PR DESCRIPTION
**Pull request by dhdaines**
Here's the new API used in the alignment demo (https://github.com/dhdaines/alignment-demo and https://aligner.ecolingui.ca/), updated for G2P 2.x.  There's also a small fix to the substring alignment code, can't quite remember what it was for but it should have coverage in any case. (EDIT: Nope actually it doesn't have coverage ... well, that will have to get fixed)

For the moment I made fastapi an optional dependency, so this should have no effect on anything else.  It is based on `dev.hatch` though, at least for the moment.

### CODE REVIEW

**Comment by joanise** [comment]
Initial clarification question: is the intent to ultimately merge both #360 and this PR, i.e., to update API v1 to use FastAPI, *and* to add this API v2?

**Comment by dhdaines** [comment]
> Initial clarification question: is the intent to ultimately merge both #360 and this PR, i.e., to update API v1 to use FastAPI, _and_ to add this API v2?

Yes, they are independent of each other, but the idea would be to add both APIs (`/api/v1` and `/api/v2`)

**Review by joanise — APPROVED** [review]
Great!
Way easier to review this one, now that the hard work is done in the other PR!

**Comment by dhdaines** [comment]
> Great! Way easier to review this one, now that the hard work was done in the other PR!

Thanks!  I'm not going to worry too much about the coverage issues for the moment...

**Pull request merged**
