### PR TITLE
Fix all CI deprecation warnings

### PR DESCRIPTION
**Pull request by joanise**
Hard to test until we do the next release, but carefully reviewed.

I suggest we merge this in now, but monitor closely when we make our next release March 1.

### CODE REVIEW

**Comment by roedoejet** [comment]
see my note here: https://github.com/ReadAlongs/Studio/pull/134#issuecomment-1340208665 

Especially considering these changes affect two release actions, I think we need to test this on a separate repo.

**Comment by joanise** [comment]
Yeah, agreed here too.

**Comment by joanise** [comment]
@roedoejet I have now tested this in a separate repo, and I can confirm that it is safe to merge.

While I was there, I have tested what happens if you make a release and delete it, should you be unhappy with it. The results are nice.
 - I deleted the release and the tag associated with it
 - I pushed a new release to my test repo
 - The new release had all the update messages from the commits that were included in the deleted commit, going right back to the previous commit that was still there.

I recommend merge this into `main` now.

**Review by roedoejet — APPROVED** [review]
Great, thanks for testing @joanise !

**Pull request merged**
